//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Sistema_de_InventarioEntities2 : DbContext
    {
        public DB_Sistema_de_InventarioEntities2()
            : base("name=DB_Sistema_de_InventarioEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tabla_Clientes> Tabla_Clientes { get; set; }
        public virtual DbSet<Tabla_Intemedia_Comrpas> Tabla_Intemedia_Comrpas { get; set; }
        public virtual DbSet<Tabla_Intermedia_Proveen> Tabla_Intermedia_Proveen { get; set; }
        public virtual DbSet<Tabla_Productos> Tabla_Productos { get; set; }
        public virtual DbSet<Tabla_Proveedores> Tabla_Proveedores { get; set; }
        public virtual DbSet<Tabla_Usuarios> Tabla_Usuarios { get; set; }
    }
}
