//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tabla_Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabla_Clientes()
        {
            this.Tabla_Intemedia_Comrpas = new HashSet<Tabla_Intemedia_Comrpas>();
        }
        [Key]
        [Display(Name ="Id")]
        public int clienteID { get; set; }
        [Display(Name = "Nombre del Cliente")]
        public string nombreCliente { get; set; }
        [Display(Name = "Apellido Paterno")]
        public string apellidoPaternoCliente { get; set; }
        [Display(Name = "Apellido Materno")]
        public string apellidoMaternoCliente { get; set; }
        [Display(Name = "Direccion del Cliente")]
        public string direccionCliente { get; set; }
        [Display(Name = "Numero de Telefono")]
        public string telefonoCliente { get; set; }
        [Display(Name = "Correo Electronico")]
        public string correroCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabla_Intemedia_Comrpas> Tabla_Intemedia_Comrpas { get; set; }
    }
}
