//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tabla_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabla_Productos()
        {
            this.Tabla_Intemedia_Comrpas = new HashSet<Tabla_Intemedia_Comrpas>();
            this.Tabla_Intermedia_Proveen = new HashSet<Tabla_Intermedia_Proveen>();
        }
        [Key]
        [Display(Name = "Id")]
        public int productoID { get; set; }
        [Display(Name = "Nombre del Producto")]
        public string nombreProducto { get; set; }
        [Display(Name = "Precio de Venta")]
        public Nullable<decimal> precioVenta { get; set; }
        [Display(Name = "Precio de Compra")]
        public Nullable<decimal> precioCompra { get; set; }
        [Display(Name = "Peso Neto")]
        public Nullable<int> pesoNeto { get; set; }
        [Display(Name = "Fecha de Entrada")]
        public Nullable<System.DateTime> fechaEntrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabla_Intemedia_Comrpas> Tabla_Intemedia_Comrpas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabla_Intermedia_Proveen> Tabla_Intermedia_Proveen { get; set; }
    }
}
