//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tabla_Usuarios
    {
        [Key]
        [Display(Name = "Id")]
        public int usuarioID { get; set; }
        [Display(Name = "Nombre del Usuario")]
        public string nombreUsuario { get; set; }
        [Display(Name = "Contraseña")]
        public string passwordUsuario { get; set; }
    }
}
