//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tabla_Intemedia_Comrpas
    {
        [Key]
        [Display(Name ="Id")]
        public int compraID { get; set; }
        [Display(Name = "ClienteID")]
        public int clienteID { get; set; }
        [Display(Name = "ProductoID")]
        public int productoID { get; set; }
        [Display(Name = "Fecha de Compra")]
        public Nullable<System.DateTime> fechaCompra { get; set; }
        [Display(Name = "Cantidad Comprada")]
        public Nullable<int> cantidad { get; set; }
    
        public virtual Tabla_Clientes Tabla_Clientes { get; set; }
        public virtual Tabla_Productos Tabla_Productos { get; set; }
    }
}
